import { Router } from 'express';
import { authRouter } from './auth/router.js';
import { matchesRouter } from './matches/router.js';
import { predictionsRouter } from './predictions/router.js';
import { leaguesRouter } from './leagues/router.js';
import { teamsRouter } from './teams/router.js';
import { playersRouter } from './players/router.js';
import { tournamentPredictionsRouter } from './tournament-predictions/router.js';
import { predictionScorersRouter } from './prediction-scorers/router.js';
import { fantasyRouter } from './fantasy/router.js';
import { pushRouter } from './push/router.js';
import { achievementsRouter } from './achievements/router.js';
import { adminRouter } from './admin/router.js';
import { usersRouter } from './users/router.js';
import { statsRouter } from './stats/router.js';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/matches', matchesRouter);
apiRouter.use('/predictions', predictionsRouter);
apiRouter.use('/leagues', leaguesRouter);
apiRouter.use('/teams', teamsRouter);
apiRouter.use('/players', playersRouter);
apiRouter.use('/tournament-predictions', tournamentPredictionsRouter);
apiRouter.use('/prediction-scorers', predictionScorersRouter);
apiRouter.use('/fantasy', fantasyRouter);
apiRouter.use('/push', pushRouter);
apiRouter.use('/achievements', achievementsRouter);
apiRouter.use('/admin', adminRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/stats', statsRouter);
